"""empty message

Revision ID: 48488d14e2b2
Revises: 8c152993e1ce
Create Date: 2019-09-26 17:17:33.673265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48488d14e2b2'
down_revision = '8c152993e1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('weight_class', sa.String(length=32), nullable=True),
    sa.Column('red_fighter', sa.String(length=64), nullable=True),
    sa.Column('blue_fighter', sa.String(length=64), nullable=True),
    sa.Column('winner', sa.String(length=64), nullable=True),
    sa.Column('loser', sa.String(length=64), nullable=True),
    sa.Column('end_round', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bouts_blue_fighter'), 'bouts', ['blue_fighter'], unique=False)
    op.create_index(op.f('ix_bouts_end_round'), 'bouts', ['end_round'], unique=False)
    op.create_index(op.f('ix_bouts_event_id'), 'bouts', ['event_id'], unique=False)
    op.create_index(op.f('ix_bouts_loser'), 'bouts', ['loser'], unique=False)
    op.create_index(op.f('ix_bouts_method'), 'bouts', ['method'], unique=False)
    op.create_index(op.f('ix_bouts_red_fighter'), 'bouts', ['red_fighter'], unique=False)
    op.create_index(op.f('ix_bouts_time'), 'bouts', ['time'], unique=False)
    op.create_index(op.f('ix_bouts_weight_class'), 'bouts', ['weight_class'], unique=False)
    op.create_index(op.f('ix_bouts_winner'), 'bouts', ['winner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bouts_winner'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_weight_class'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_time'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_red_fighter'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_method'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_loser'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_event_id'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_end_round'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_blue_fighter'), table_name='bouts')
    op.drop_table('bouts')
    # ### end Alembic commands ###
