"""empty message

Revision ID: 77a653653048
Revises: b3c1ccc752e0
Create Date: 2019-09-29 13:51:40.382834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a653653048'
down_revision = 'b3c1ccc752e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bouts', sa.Column('b_KD', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('b_PASS', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('b_SIGSTR', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('b_SIGSTR_PRCT', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('b_SUB', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('b_TD', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('b_TD_PRCT', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('b_TTLSTR', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('b_TTLSTR_PRCT', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('r_KD', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('r_PASS', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('r_SIGSTR', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('r_SIGSTR_PRCT', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('r_SUB', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('r_TD', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('r_TD_PRCT', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('r_TTLSTR', sa.String(length=12), nullable=True))
    op.add_column('bouts', sa.Column('r_TTLSTR_PRCT', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_bouts_b_KD'), 'bouts', ['b_KD'], unique=False)
    op.create_index(op.f('ix_bouts_b_PASS'), 'bouts', ['b_PASS'], unique=False)
    op.create_index(op.f('ix_bouts_b_SIGSTR'), 'bouts', ['b_SIGSTR'], unique=False)
    op.create_index(op.f('ix_bouts_b_SIGSTR_PRCT'), 'bouts', ['b_SIGSTR_PRCT'], unique=False)
    op.create_index(op.f('ix_bouts_b_SUB'), 'bouts', ['b_SUB'], unique=False)
    op.create_index(op.f('ix_bouts_b_TD'), 'bouts', ['b_TD'], unique=False)
    op.create_index(op.f('ix_bouts_b_TD_PRCT'), 'bouts', ['b_TD_PRCT'], unique=False)
    op.create_index(op.f('ix_bouts_b_TTLSTR'), 'bouts', ['b_TTLSTR'], unique=False)
    op.create_index(op.f('ix_bouts_b_TTLSTR_PRCT'), 'bouts', ['b_TTLSTR_PRCT'], unique=False)
    op.create_index(op.f('ix_bouts_r_KD'), 'bouts', ['r_KD'], unique=False)
    op.create_index(op.f('ix_bouts_r_PASS'), 'bouts', ['r_PASS'], unique=False)
    op.create_index(op.f('ix_bouts_r_SIGSTR'), 'bouts', ['r_SIGSTR'], unique=False)
    op.create_index(op.f('ix_bouts_r_SIGSTR_PRCT'), 'bouts', ['r_SIGSTR_PRCT'], unique=False)
    op.create_index(op.f('ix_bouts_r_SUB'), 'bouts', ['r_SUB'], unique=False)
    op.create_index(op.f('ix_bouts_r_TD'), 'bouts', ['r_TD'], unique=False)
    op.create_index(op.f('ix_bouts_r_TD_PRCT'), 'bouts', ['r_TD_PRCT'], unique=False)
    op.create_index(op.f('ix_bouts_r_TTLSTR'), 'bouts', ['r_TTLSTR'], unique=False)
    op.create_index(op.f('ix_bouts_r_TTLSTR_PRCT'), 'bouts', ['r_TTLSTR_PRCT'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bouts_r_TTLSTR_PRCT'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_TTLSTR'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_TD_PRCT'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_TD'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_SUB'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_SIGSTR_PRCT'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_SIGSTR'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_PASS'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_r_KD'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_TTLSTR_PRCT'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_TTLSTR'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_TD_PRCT'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_TD'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_SUB'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_SIGSTR_PRCT'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_SIGSTR'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_PASS'), table_name='bouts')
    op.drop_index(op.f('ix_bouts_b_KD'), table_name='bouts')
    op.drop_column('bouts', 'r_TTLSTR_PRCT')
    op.drop_column('bouts', 'r_TTLSTR')
    op.drop_column('bouts', 'r_TD_PRCT')
    op.drop_column('bouts', 'r_TD')
    op.drop_column('bouts', 'r_SUB')
    op.drop_column('bouts', 'r_SIGSTR_PRCT')
    op.drop_column('bouts', 'r_SIGSTR')
    op.drop_column('bouts', 'r_PASS')
    op.drop_column('bouts', 'r_KD')
    op.drop_column('bouts', 'b_TTLSTR_PRCT')
    op.drop_column('bouts', 'b_TTLSTR')
    op.drop_column('bouts', 'b_TD_PRCT')
    op.drop_column('bouts', 'b_TD')
    op.drop_column('bouts', 'b_SUB')
    op.drop_column('bouts', 'b_SIGSTR_PRCT')
    op.drop_column('bouts', 'b_SIGSTR')
    op.drop_column('bouts', 'b_PASS')
    op.drop_column('bouts', 'b_KD')
    # ### end Alembic commands ###
