"""empty message

Revision ID: 8c152993e1ce
Revises: 9d11ff6dd36f
Create Date: 2019-09-25 15:34:33.775475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c152993e1ce'
down_revision = '9d11ff6dd36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_event', table_name='events')
    op.create_index(op.f('ix_events_event'), 'events', ['event'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event'), table_name='events')
    op.create_index('ix_events_event', 'events', ['event'], unique=1)
    # ### end Alembic commands ###
