"""empty message

Revision ID: d160173b845e
Revises: 77a653653048
Create Date: 2019-09-29 18:06:00.634246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd160173b845e'
down_revision = '77a653653048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bouts_b_TTLSTR_PRCT', table_name='bouts')
    op.drop_index('ix_bouts_r_TTLSTR_PRCT', table_name='bouts')
    op.drop_column('bouts', 'r_TTLSTR_PRCT')
    op.drop_column('bouts', 'b_TTLSTR_PRCT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bouts', sa.Column('b_TTLSTR_PRCT', sa.VARCHAR(length=12), nullable=True))
    op.add_column('bouts', sa.Column('r_TTLSTR_PRCT', sa.VARCHAR(length=12), nullable=True))
    op.create_index('ix_bouts_r_TTLSTR_PRCT', 'bouts', ['r_TTLSTR_PRCT'], unique=False)
    op.create_index('ix_bouts_b_TTLSTR_PRCT', 'bouts', ['b_TTLSTR_PRCT'], unique=False)
    # ### end Alembic commands ###
